version: 0.2



phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
      - REPOSITORY_URI=944115548643.dkr.ecr.us-east-1.amazonaws.com/nginximage
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=build-$(echo $CODEBUILD_BUILD_ID | awk -F":" '{print $2}')
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t 944115548643.dkr.ecr.us-east-1.amazonaws.com/nginximage:latest .
      - docker tag 944115548643.dkr.ecr.us-east-1.amazonaws.com/nginximage:latest 944115548643.dkr.ecr.us-east-1.amazonaws.com/nginximage:tag2
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push 944115548643.dkr.ecr.us-east-1.amazonaws.com/nginximage:latest
      - docker push 944115548643.dkr.ecr.us-east-1.amazonaws.com/nginximage:tag2
      - echo Writing image definitions file...
      - printf '[{"name":"nginx","imageUri":"%s"}]' 944115548643.dkr.ecr.us-east-1.amazonaws.com/nginximage:tag2 > imagedefinitions.json
      - cat imagedefinitions.json 
artifacts:
    files: imagedefinitions.json
